### PR TITLE
Update breaking-down-identity.md

### PR DESCRIPTION
**Pull request by hoppeday**

### CODE REVIEW

**Comment by susanev** [comment]
Hi @hoppeday you do not need to do pull requests for your responses, since then your responses would be part of everyones curriculum. Feel free to commit directly to your version. If you have questions about this feel free to reach out.

**Comment by hoppeday** [comment]
Should I just save them in my repository?

**Comment by susanev** [comment]
Yes

**Comment by hoppeday** [comment]
Thank you!

**Pull request closed without merging**
